In [3]:
# Import necessary libraries
import neurolab as nl
import numpy as np

# Exercise # 1:
Single Layer Feed Forward to Recognize Sum Pattern (20 marks)

Requirements:

1. **Create the training data (input):**
   - Use `numpy` to generate two sets of 10 numbers drawn from a uniform distribution. Set the numbers to fall between -0.6 and +0.6.
   - Save these numbers in a 10 by 2 `ndarray`, where each set is considered a feature.
   - Name the `ndarray` as `input_firstname`, where `firstname` is your first name.

2. **Create the target data (output):**
   - The target output is the sum of the two random values for each instance of the input data.
   - For example:

     | Input Data   | Output Data |
     |--------------|-------------|
     | 0.1   0.45   | 0.55        |
     | 0.035 0.21   | 0.245       |
     | ...   ...    | ...         |

     i.e., \( y = x_1 + x_2 \)

   - Store the output in a `ndarray` of size 10 by 1.
   - Name this `ndarray` as `output_firstname`, where `firstname` is your first name.

3. **Set the seed:** `seed = 1`

4. **Using `neurolab`, create a simple neural network:**
   - The network should have:
     - Two inputs
     - Six neurons in a single layer
     - One output

5. **Train the network** using the input and output data created in points 1 and 2.
   - Set the following parameters:
     - `show=15`
     - `goal=0.00001`

6. **Train the network** using the 10 data points.

7. **Test / Simulate the network:**
   - Pass the following test values: 0.1 and 0.2
   - Record the result under **result #1**.


In [4]:
# 1. Create the training data(input):
# 2. Generating the training data (input)
input_beta = np.random.uniform(-0.6, 0.6, (10, 2))
print("Generated Input (input_beta):\n", input_beta)

Generated Input (input_beta):
 [[ 0.16754527 -0.4345532 ]
 [ 0.56410387  0.09429837]
 [ 0.34830393  0.12471413]
 [ 0.01541224 -0.125115  ]
 [-0.20940046  0.40414156]
 [ 0.57924423  0.01933473]
 [-0.16472714  0.05830873]
 [ 0.4569988   0.32199686]
 [ 0.27170288  0.517021  ]
 [ 0.00750782  0.39265213]]


In [5]:
# 3. Creating the target data (output)
output_beta = np.sum(input_beta, axis=1).reshape(10, 1)
print("Generated Output (output_beta):\n", output_beta)

Generated Output (output_beta):
 [[-0.26700793]
 [ 0.65840224]
 [ 0.47301806]
 [-0.10970277]
 [ 0.19474109]
 [ 0.59857896]
 [-0.10641841]
 [ 0.77899565]
 [ 0.78872389]
 [ 0.40015995]]


In [6]:
# 4.1 Setting seed to 1
np.random.seed(1)

In [7]:
# 5. Setting up the neural network
input_range = [[-0.6, 0.6], [-0.6, 0.6]]
net = nl.net.newff(input_range, [6, 1])

In [8]:
# 6. Setting training parameters and 7. Training the network using the 10 data points.
net.trainf = nl.train.train_gd  # Set training function to gradient descent
error = net.train(input_beta, output_beta, show=15, goal=0.00001)

Epoch: 15; Error: 0.25291552107598836;
Epoch: 30; Error: 0.20454669859899993;
Epoch: 45; Error: 0.17603485971501526;
Epoch: 60; Error: 0.15566198160813272;
Epoch: 75; Error: 0.141011620119376;
Epoch: 90; Error: 0.1302936225610576;
Epoch: 105; Error: 0.12212377426860503;
Epoch: 120; Error: 0.11555549974481173;
Epoch: 135; Error: 0.10999262157712787;
Epoch: 150; Error: 0.10507704291936731;
Epoch: 165; Error: 0.10059910010940154;
Epoch: 180; Error: 0.09643744554549422;
Epoch: 195; Error: 0.09252194357043732;
Epoch: 210; Error: 0.08881173723864677;
Epoch: 225; Error: 0.08528257293175796;
Epoch: 240; Error: 0.08191955515965882;
Epoch: 255; Error: 0.07871302203969008;
Epoch: 270; Error: 0.0756561974526256;
Epoch: 285; Error: 0.07274385236241139;
Epoch: 300; Error: 0.06997154090676311;
Epoch: 315; Error: 0.06733516604054623;
Epoch: 330; Error: 0.06483073601528401;
Epoch: 345; Error: 0.06245423273890525;
Epoch: 360; Error: 0.06020154660809904;
Epoch: 375; Error: 0.05806845130565944;
Epoch: 390

In [9]:
# 8. Testing the network
test_input = np.array([[0.1, 0.2]])
result_1 = net.sim(test_input)
print("Result for test input [0.1, 0.2]:", result_1)

Result for test input [0.1, 0.2]: [[0.408845]]


# Exercise # 2:
Multi-Layer Feed Forward to Recognize Sum Pattern (20 marks)

1. **Repeat steps 1-8 from Exercise #1** except for step #5, where you will:
   - Create a two-layer feed-forward network, i.e., two hidden layers:
     - The first hidden layer with 5 neurons
     - The second hidden layer with 3 neurons
   - Set the following parameters:
     - `epochs=1000`
     - `show=100`
     - `goal=0.00001`

2. **Record the result** under **result #2**.

3. **Set the training algorithm** to Gradient Descent Backpropagation.

4. **Written Response**:
   - Compare **result #1** to **result #2** and to the actual result.
   - Explain your findings.


In [10]:
# 1. Create the training data(input):
# 2. Generating the training data (input)
input_beta = np.random.uniform(-0.6, 0.6, (10, 2))
print("Generated Input (input_beta):\n", input_beta)

Generated Input (input_beta):
 [[-0.43153567 -0.36227821]
 [ 0.36089348  0.56191389]
 [-0.22389099  0.23078714]
 [ 0.45166698  0.473528  ]
 [-0.49794695 -0.55313426]
 [-0.3962035   0.453771  ]
 [-0.4819838  -0.09467085]
 [ 0.54946744  0.03979834]
 [ 0.23025254 -0.22138124]
 [ 0.22380111  0.40155081]]


In [11]:
# 3. Creating the target data (output)
output_beta = np.sum(input_beta, axis=1).reshape(10, 1)
print("Generated Output (output_beta):\n", output_beta)

Generated Output (output_beta):
 [[-0.79381389]
 [ 0.92280737]
 [ 0.00689615]
 [ 0.92519498]
 [-1.05108121]
 [ 0.05756751]
 [-0.57665465]
 [ 0.58926578]
 [ 0.00887129]
 [ 0.62535192]]


In [12]:
# 4. Setting seed to 1
np.random.seed(1)

In [13]:
# 5. Setting up the neural network: 5 neurons in the first layer, 3 in the second, 1 output
input_range = [[-0.6, 0.6], [-0.6, 0.6]]
net = nl.net.newff(input_range, [5, 3, 1])

In [14]:
# 6. Setting training parameters: epochs=1000, show=100, goal=0.00001
# 7. Training the network using the 10 data points.
net.trainf = nl.train.train_gd  # train_gd provides gradient descent with backpropagation
error = net.train(input_beta, output_beta, epochs=1000, show=100, goal=0.00001)

Epoch: 100; Error: 0.49594434110722835;
Epoch: 200; Error: 0.43612509719028464;
Epoch: 300; Error: 0.366132765364826;
Epoch: 400; Error: 0.2627629316348087;
Epoch: 500; Error: 0.17763969459287274;
Epoch: 600; Error: 0.13591220973394372;
Epoch: 700; Error: 0.11447439735414333;
Epoch: 800; Error: 0.10397911535689794;
Epoch: 900; Error: 0.09913731931714065;
Epoch: 1000; Error: 0.09679992618680057;
The maximum number of train epochs is reached


In [16]:
# 8. Testing the network
test_input = np.array([[0.1, 0.2]])
result_2 = net.sim(test_input)
print("Result for test input [0.1, 0.2]:", result_2)

Result for test input [0.1, 0.2]: [[0.50169851]]


# Exercise # 3:
Single-Layer Feed Forward to Recognize Sum Pattern with More Training Data (20 marks)

1. **Repeat steps 1-3 from Exercise #1**:
   - Generate 100 random instances this time instead of 10.

2. **Repeat steps 4-8 from Exercise #1**.

3. **Record the result** as **result #3**.

4. **Written Response**:
   - Compare **result #1** to **result #3** and to the actual result.
   - Explain your findings.


# Exercise # 4:
Multi-Layer Feed Forward to Recognize Sum Pattern with More Training Data (20 marks)

1. **Repeat step #1 in Exercise #3**:
   - Generate 100 random samples as the training data.

2. **Create a two-layer feed-forward network**:
   - Two hidden layers:
     - The first hidden layer with 5 neurons
     - The second hidden layer with 3 neurons
   - Set the following parameters:
     - `epochs=1000`
     - `show=100`
     - `goal=0.00001`

3. **Set the training algorithm** to Gradient Descent Backpropagation.

4. **Train the network** using the 100 data points.

5. **Plot the error vs. training size** graph.

6. **Test / Simulate the network**:
   - Pass the following test values: 0.1 and 0.2.
   - Record the result under **result #4**.

7. **Written Response**:
   - Compare **result #3** to **result #4** and to the actual result.
   - Explain your findings.


# Exercise # 5:
Three-Input Multi-Layer Feed Forward to Recognize Sum Pattern with More Training Data (20 marks)

1. **Repeat Exercise #1**:
   - Instead of two inputs, generate **three inputs** for the training data.

2. **Test / Simulate the Network**:
   - Use the test sample `[0.2, 0.1, 0.2]`.
   - Record the results as **result #5**.

3. **Repeat Exercise #4**:
   - Modify it to have **three inputs** instead of two.

4. **Test / Simulate the Network**:
   - Use the test sample `[0.2, 0.1, 0.2]`.
   - Record the results as **result #6**.

5. **Written Response**:
   - Compare **result #5** to **result #6** and to the actual result.
   - Explain your findings.
